version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"
      - run: sleep 25
  buildx:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A  more familiar hi"
      - run: sleep 25
workflows:
  version: 2
  one_and_two:
    jobs:
      - build
      - buildx
